server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Class
          uri: http://localhost:8081
          predicates:
            - Path=/classes/**, 
        - id: Enrollment
          uri: http://localhost:8082
          predicates:
            - Path=/enrollments/**, 
        - id: Student
          uri: http://localhost:8083
          predicates:
            - Path=/students/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Class
          uri: http://class:8080
          predicates:
            - Path=/classes/**, 
        - id: Enrollment
          uri: http://enrollment:8080
          predicates:
            - Path=/enrollments/**, 
        - id: Student
          uri: http://student:8080
          predicates:
            - Path=/students/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
